var numero1=8;
var numero2=10;

if(numero1>numero2){
    console.log("El numero sí es mayor");
}

else if(numero1==numero2){

    console.log("Ambos numeros son iguales");
}

else{
    console.log("El numero 1 es menor"); 
}

var nombre="Yazmyn";

console.log(nombre.length);

if (nombre.length>7){
console.log("Tu nombre es muy largo")
}

else{
    console.log("Tu nombre es de tamaño normal")
}